### ISSUE TITLE
Roadmap to v0.1.0

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#12]
- [x] Remove `gaze` from deps.
- [x] Add `add` and `unlink` to the watcher.
- [x] **Support Flyfiles written in ES6-7, CoffeeScript, etc.**
- [x] Add CHANGELOG
- [x] Improve plugin and watch API
- [x] `Fly.prototype.reset` should be private.
- [x] Add CLI documentation.
- [x] Change main example using coffee to babel (makes sense considering the project is written in Babel).

**Comment by watilde** [comment]
My comment on gitter for this issue:

> @bucaran This roadmap for v0.0.5 includes some feature improvements. IMHO you need to update feature version for using semver. flyjs/fly#12

**Comment by ghost** [comment]
Roadmap to v0.0.5 has been renamed to _Roadmap to v0.1.0_

**Comment by watilde** [comment]
@bucaran Great! You can also create a release tag too: https://github.com/flyjs/fly/releases/new

**Comment by ghost** [comment]
Done.

**Comment by watilde** [comment]
:+1: :+1:
