### ISSUE TITLE
website requirements

### ISSUE THREAD

**Issue by tomByrer** [lukeed/taskr#158]
Technical
- [ ]  build tool using fly  :bulb: 
- [ ]  easy for others to learn & help
  - no heavy frameworks like Angular, React, etc
  - well commented
- [ ]  well linted, tooling enforces code (XO `.eslint` defaults, `.editorconfig`...)
- [ ]  also outputs Markdown for Github viewing
  - .md source?

Layout
- [ ] mobile friendly
  - OK if API pages don't work on phone, but should on tablet
- [ ] examples
  - live editor, or save bandwidth by linking to editor & only static results?
  - landing page should have some examples
  - using fly with other build tools (like gulp, Webpack, rollup)
- pagelist
  - home
  - API
  - tutorial (or examples if not in API)
  - community
    - where to get help
    - projects using fly
  - compare to other build tools (or just mentioned in home page)

**Comment by ghost** [comment]
@tomByrer Great start! Thanks man.

**Comment by tomByrer** [comment]
ref: https://github.com/bucaran/fly/issues/23

Above at this moment is only my brainstorm, will edit as things are decided on.  I'd love to hear other input.  I may or may not have time to actually work on this.
I have my own opinion on stack (PostCSS, [verb](https://github.com/verbose/verb/tree/dev), but really if someone else has more time & already tooled for a different stack, then that's fine.

Could be launched in stages; just landing, then move docs from WiKi to website later.

**Comment by lukeed** [comment]
The [Web Kit](https://github.com/lukeed/fly-kit-web) would be the best way to get going quickly.

**Comment by ghost** [comment]
Here are some dummy ideas. I was thinking something like crazy giant letters and ultra blue. Would this be the in direction we want?

![screen shot 2016-04-09 at 1 42 19 am](https://cloud.githubusercontent.com/assets/8317250/14390853/260bc03e-fdf4-11e5-875e-ef1a0983ca59.png)
![screen shot 2016-04-09 at 1 42 24 am](https://cloud.githubusercontent.com/assets/8317250/14390854/260c2ab0-fdf4-11e5-9995-b088738eca51.png)
![screen shot 2016-04-09 at 1 41 42 am](https://cloud.githubusercontent.com/assets/8317250/14390852/260b839e-fdf4-11e5-9db9-97984d535bf3.png)
![screen shot 2016-04-09 at 1 41 47 am](https://cloud.githubusercontent.com/assets/8317250/14390855/260d3b76-fdf4-11e5-9454-921db4c0afcf.png)

**Comment by tomByrer** [comment]
Sorry I wasn't clear about my first post.  I expected requirements to be formed before design is started; if you don't know your business objectives, you won't know if the proposed deigns will meet the requirements.

Personally, I'm really only interested if fly is better enough from gulp to make the effort to switch.  I assume I represent the majority of visitors, but I'm open to be totally wrong.

**Comment by ghost** [comment]
Fair enough. I agree with all the technical requirements. As for the layout, I'd love to comply with all of it, but it seems too ambitious. Are we actually going to do all of it?

Other than the plugin search feature, gulpjs.com is quite simple, which is what I was thinking when I originally proposed the idea.

**Comment by lukeed** [comment]
I'm on the same page as @tomByrer; and they're exactly what I had in mind for the site too.

If a framework or ecosystem doesn't have a site with _at least_ those aspects, then there's no use in having a site. 

Gulp's website is a placeholder, at best. They can only "afford" to leave it as such because (1) everyone already uses it and (2) the community has filled in the gaps with much-needed resources and documentation.

**Comment by tomByrer** [comment]
Those are neat ideas @bucaran; I don't want to sound dismissive.
For me `compare to other build tools` is the most important; I'm personally not convinced to switch from gulp/webpack to fly either.

**Comment by lukeed** [comment]
@tomByrer @bucaran When i get something pushable together, I'll ping all of you so we're on the same page every step of the way. 👍

**Comment by tomByrer** [comment]
TY.
I added another thought:

> using fly with other build tools (like gulp, Webpack, rollup)

Perhaps people don't want to re-write their entire gruntfile, but fly is better at one part of the build process.  I consider Webpack & such built tools also, but perhaps fly could help with pre-pre-processing, or post-processing?

**Comment by lukeed** [comment]
There's already integration with [webpack](https://github.com/andrewsokolov/fly-webpack) and there's discussion of Rollup integration here: #113 

Fly should never be integrated with Gulp/Grunt (my opinion) because then it'd be too many cooks in the kitchen. They all serve the same purpose and will mostly get in each other way. Similarly, you'll never integrate Gulp with Grunt, because one can do exactly what the other can.

**Comment by lukeed** [comment]
Closing since this is no longer on our radar (for now) and hasn't seen any activity in a year 😆 

Still agree with the bullet list, but still, likely not something we'll do anytime soon~

Thanks! 🏅
